[project]
name = "pyskeleton-interfaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.15.2"
    ]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
# 
# [tool.hatch.build.targets.wheel]
# packages = ["src/pyskeleton_interfaces",
# "pyskeleton-core/src",
# "project-template"
# ]
# artifacts = [
#   "project-template/**/*",
# ]

