[project]
name = "template-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "filetype>=1.2.0",
    "numpy>=2.2.5",
    "pillow>=11.2.1",
    "pypdf[crypto]>=5.4.0",
    "toml>=0.10.2",
    "trio-asyncio>=0.15.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
